export const ALERT_TYPE = {
    CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
    CAMPAIGN_UPDATED: "CAMPAIGN_UPDATED",
    APPLICATION_RECEIVED: "APPLICATION_RECEIVED",
    APPLICATION_ACCEPTED: "APPLICATION_ACCEPTED",
    APPLICATION_REJECTED: "APPLICATION_REJECTED",
    PROPOSAL_RECEIVED: "PROPOSAL_RECEIVED",
    PROPOSAL_ACCEPTED: "PROPOSAL_ACCEPTED",
    PROPOSAL_REJECTED: "PROPOSAL_REJECTED",
    SYSTEM_NOTIFICATION: "SYSTEM_NOTIFICATION",
} as const;

export const ALERT_TYPE_LABELS = {
    [ALERT_TYPE.CAMPAIGN_CREATED]: "캠페인 생성",
    [ALERT_TYPE.CAMPAIGN_UPDATED]: "캠페인 업데이트",
    [ALERT_TYPE.APPLICATION_RECEIVED]: "지원서 접수",
    [ALERT_TYPE.APPLICATION_ACCEPTED]: "지원 승인",
    [ALERT_TYPE.APPLICATION_REJECTED]: "지원 거절",
    [ALERT_TYPE.PROPOSAL_RECEIVED]: "제안 접수",
    [ALERT_TYPE.PROPOSAL_ACCEPTED]: "제안 승인",
    [ALERT_TYPE.PROPOSAL_REJECTED]: "제안 거절",
    [ALERT_TYPE.SYSTEM_NOTIFICATION]: "시스템 알림",
} as const;

export const ALERT_STATUS = {
    UNREAD: "UNREAD",
    READ: "READ",
    ARCHIVED: "ARCHIVED",
} as const;

export const ALERT_STATUS_LABELS = {
    [ALERT_STATUS.UNREAD]: "읽지 않음",
    [ALERT_STATUS.READ]: "읽음",
    [ALERT_STATUS.ARCHIVED]: "보관됨",
} as const; 